### ISSUE TITLE
PHP Fatal Error logging in over OpenID

### ISSUE THREAD

**Issue by unikent-ms1** [simplesamlphp/simplesamlphp-module-openidprovider#1]
Latest SimpleSAMLphp distribution (1.13.2) set up to enable OpenID provider module (and with relevant include fixes detailed in https://groups.google.com/forum/#!topic/simplesamlphp/mV6eOxEFBt8) and attempting to hit http://openid-consumer.appspot.com as a simple test fails with:

PHP Fatal error:  Call to undefined method Auth_OpenID_AX_Error::iterTypes() in .../modules/openidProvider/lib/Server.php on line 456

Doing a print_r on the $ax_req object after it's been generated reports:

Auth_OpenID_AX_Error Object ( [message] => Expected mode 'fetch_request'; got '' )

This error is not being caught properly and then the code tries to hit a
function on the expected object (iterTypes()) which barfs because it's
the wrong object (at line 456).

Commenting out that forloop results in a "working" (albeit empty)
response to the consumer rather than PHP death.

**Comment by unikent-ms1** [comment]
Been poking this a bit more… looks like `fromOpenIDRequest()` is getting something wrong and passing an emptyish object into `parseExtensionArgs()` (which then gets down to `_checkMode()` which fails):

``` php
    static function fromOpenIDRequest($request)
    {
        $m = $request->message;
        $obj = new Auth_OpenID_AX_FetchRequest();
        $ax_args = $m->getArgs($obj->ns_uri);

        $result = $obj->parseExtensionArgs($ax_args);

        if (Auth_OpenID_AX::isError($result)) {
            return $result;
        }
        ...
    }
```

Backtrace called from the top of `_checkMode()` (full backtrace available if you need it):

```
#0  Auth_OpenID_AX_Message->_checkMode(Array ()) called at [.../simplesamlphp-1.13.2/vendor/openid/php-openid/Auth/OpenID/AX.php:437]
#1  Auth_OpenID_AX_FetchRequest->parseExtensionArgs(Array ()) called at [.../simplesamlphp-1.13.2/vendor/openid/php-openid/Auth/OpenID/AX.php:398]
#2  Auth_OpenID_AX_FetchRequest::fromOpenIDRequest(Auth_OpenID_CheckIDRequest Object (...) called at [.../simplesamlphp-1.13.2/modules/openidProvider/lib/Server.php:392]
#3  sspmod_openidProvider_Server->processRequest(Array (...)) called at [.../simplesamlphp-1.13.2/modules/openidProvider/lib/Server.php:488]
#4  sspmod_openidProvider_Server->receiveRequest() called at [.../simplesamlphp-1.13.2/modules/openidProvider/www/server.php:6]
#5  require(.../simplesamlphp-1.13.2/modules/openidProvider/www/server.php) called at [.../simplesamlphp-1.13.2/www/module.php:134]
```

**Comment by jaimeperez** [comment]
Hi @unikent-ms1, thanks for reporting this!

Could you please tell me if this patch works for you?

``` patch
diff --git a/lib/Server.php b/lib/Server.php
index b132ac6..aa3f955 100644
--- a/lib/Server.php
+++ b/lib/Server.php
@@ -12,8 +12,8 @@ if (defined('E_DEPRECATED')) {

 /* Add the OpenID library search path. */
 set_include_path(get_include_path() . PATH_SEPARATOR . dirname(dirname(dirname(dirname(__FILE__)))) . '/lib');
-include_once  dirname(dirname(dirname(dirname(__FILE__)))) . '/lib/Auth/OpenID/SReg.php';
-include_once  dirname(dirname(dirname(dirname(__FILE__)))) . '/lib/Auth/OpenID/AX.php';
+include_once('Auth/OpenID/SReg.php');
+include_once('Auth/OpenID/AX.php');

 /**
  * Helper class for the OpenID provider code.
@@ -453,13 +453,15 @@ class sspmod_openidProvider_Server {
        $sreg_resp->toMessage($response->fields);

        //Process AX requests
-       $ax_resp = new Auth_OpenID_AX_FetchResponse();
-       foreach($ax_req->iterTypes() as $type_uri) {
-            if(isset($attributes[$type_uri])) {
+        if (!Auth_OpenID_AX::isError($ax_req)) {
+            $ax_resp = new Auth_OpenID_AX_FetchResponse();
+            foreach ($ax_req->iterTypes() as $type_uri) {
+                if (isset($attributes[$type_uri])) {
                     $ax_resp->addValue($type_uri, $attributes[$type_uri]);
+                }
             }
-       }
-       $ax_resp->toMessage($response->fields);
+            $ax_resp->toMessage($response->fields);
+        }

        /* The user is authenticated, and trusts this site. */
        $this->sendResponse($response);
```

**Comment by fooflington** [comment]
@jaimeperez thanks for this. I have merged the patches against a new 1.13.2 install. The second hunk failed to get applied by patch but I've manually applied it instead.

I have also tested it against http://openid-consumer.appspot.com/login and it doesn't throw nasty errors any more. It doesn't appear to be releasing any attributes (but then I can't see a way to tell it to!) – should it?

Thankyou!

**Comment by jaimeperez** [comment]
Uhm, it's strange that it didn't apply smooth on a 1.13.2... I don't recall anything changing in there apart from the module being now extracted out from SSP, but that shouldn't affect you as the paths are still the same.

Regarding the attributes, I honestly have no idea :-( The only thing I can recommend you is to try with [a version previous to the problematic patch](https://raw.githubusercontent.com/simplesamlphp/simplesamlphp-module-openidprovider/c5524916c04535715e1766f3968d4c28414a5ed7/lib/Server.php). Substitute the `modules/openidProvider/lib/Server.php` file with that one, and do the same tests. Does anything change then?

**Comment by molecularbear** [comment]
I was also getting back an empty attributes array when I was testing this. I did some debugging and traced my issue to here: https://github.com/openid/php-openid/blob/a287b2d85e753c84b3b883ed8ee3ffe8692c8477/Auth/OpenID/SReg.php#L450

My test authsource (`exampleauth:Static`) config simply didn't have the requested attributes set, and therefore none were returned.

Also recommend always testing this sort of thing in incognito mode since it's easy to forget what state your session is in.

**Comment by jaimeperez** [comment]
Thanks for the input @molecularbear!
